---
title: "Balance and play in an Academic Environment"
author: "Victoria Parizot"
date: "11/08/2024"
categories:
  - reflection
draft: false
---

Something on my mind this week has been balance. 

I think perhaps one of the most important elements to a sustainable existence is balance. I've been told this my entire life -- I have to finish my homework before I could play outside, I need to eat a balanced meal, I must maintain a proper work-life balance, and so on. 

When I was younger, I did these things because my mom told me to, and a tiny part of me knew that I should for the sake of future me. If I don't finish my homework, I would get in trouble. If I don't eat my vegetables, then I would feel sick and tired later in the day. However, as I got older I realized that this relationship also goes vice-versa. An existence of only doing homework and eating brocolli would be quite monotone and boring. 

In this case, the act of play is necessary. For me, this looks like incorporating time to hang out with friends, make projects in the wood shop, go to the gym, and so on. I find that when I make time for play, I have more motivation and positivity when I do my work. I engage more with my classes, and as a result learn more.

This isn't to say that sacrifices don't have to be made. I don't necessarily think that losing balance for a short period of time is bad. In fact, I almost plan for it -- I know that during final's week, most of my time will be spent on academics, and I'll have less time for play. This allows me to adapt to the varying needs for different weeks. However, I think it can be easy to get wrapped up by this grind, and lose balance in the long term. And when I find myself 


I think balance is also something Harvey Mudd strives for. 

## Harvey Mudd College seeks to educate engineers, scientists and mathematicians well versed in all of these areas and in the humanities, social sciences and the arts so that they may assume leadership in their fields with a clear understanding of the impact of their work on society.

Take for example the Core Curriculum, Mudd's attempt to make students well versed in all the sciences, to create well rounded 


Nonetheless, I think it can sometimes be helpful to take a step back from the continuous rigor here at mudd, and ensure that fullfillment. 

And making time for your hobbies, friends, play