---
title: "AI Chat Bots: Kahnmigo + Chat GPT"
author: "Victoria Parizot"
date: "9/11/24"
categories:
  - reflection
draft: false
---
A few weeks ago, Sal Khan came to speak at my school. I remember watching his videos when I was young to learn how to factor and simplify exponents -- so I had to go to his talk. In his talk, he talked about Khanmigo, Khan Academy's AI-Powered teaching assistant. He explained its many benefits, including helping students complete assignments and assisting teachers create lesson plans through personal, albeit experimental, help. His perspective of using AI as an assistant emphasized increased throughput while still preserving effort, allowing teachers and students to be more effective with their time. 

Hearing about AI being incorporated into a platform that I grew up using was exciting to me. In the past year, we have witnessed a crazy progression of AI as it gets incorporated into existing products -- Nearly every search engine includes  AI generated answers, Adobe products have started to include generative fill, and social media has started using AI to maximize engagement. Like many, I am suprised by how quickly AI Chat Bots have improved.

I remember last winter break showing my mom ChatGPT. I just completed a class on Zora Neale Hurston, with my final paper analyzing one of her books. In an effort to show my mom how quickly ChatGPT can generate content, I asked it to create a final paper for the same prompt, using my original bare-bone outline. We were both impressed as ChatGPT delivered a polished paper, including quotations and references to her other works. However, upon closer inspection, I realized that I did not recall any of the ChatGPT proclaimed quotes from the book. Instead, these 'quotes' were made up to support ChatGPT's arguments, using the similair langauge style that Hurston had used. 

This caused me to reconsider the strengths and weaknesses of AI Chat Bots. They can be useful in idea generation and pointing someone in the general direction, however lose accuracy in details. 

With this personal experience under my belt, I was hesitant at Sal Khan's optimism about Khanmigo. What would happen in Khanmigo was  wrong about something as a student learns the fundamentals? 

Upon hearing more of his talk, I felt reassured about the testing and features that they have choosed Khanmigo to support. It is refreshing to see AI used to increase the efficiency of learning, rather than as a way to avoid learning. 



